import type { Metadata } from "next";
import {
  Aladin,
  Alegreya,
  Aleo,
  Arvo,
  Besley,
  Graduate,
  Inter,
  Lato,
  Modern_Antiqua,
  Montserrat,
  Open_Sans,
  Poppins,
  Roboto_Slab,
  Rokkitt,
  Zen_Antique_Soft,
} from "next/font/google";
import "./globals.css";

const inter = Poppins({ subsets: ["latin"], weight: ["500"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
